#!/usr/bin/env python
"""
pyspike_brian2_export.py — export a pyspike Net to Brian2-compatible Python
code. Spikeling has its own custom C/hardware backend (compiler.py's
CCodeGenerator) but no interop with any established neuromorphic simulator
ecosystem (Brian2, NEST, PyNN) or hardware target (Loihi, SpiNNaker). This
closes the Brian2 half of that gap.

HONESTY NOTE, stated up front: brian2 is NOT installed in this environment
(checked before writing this: `import brian2` -> ModuleNotFoundError). The
generated code is verified to be syntactically valid Python and structurally
matches Brian2's documented API shape (NeuronGroup, Synapses, run()) from
its own documentation -- it has NOT been executed inside a real Brian2
installation, so "produces the same result as the source network" is NOT a
claim made here. That would need brian2 actually installed and run, which
this environment cannot do right now. Verified: syntax-valid, structurally
faithful to the AST. Not verified: numerically equivalent Brian2 execution.

Brian2's LIF-equivalent is expressed via its own diff-eq string DSL:
    dv/dt = -v/tau : 1
    v += w   (on pre-synaptic spike, via Synapses' on_pre)
Spikeling's LIF is discrete-tick (v -= leak per tick, v += drive on
stimulate, v=0 and fire on threshold crossing) -- translated here into an
equivalent Brian2 continuous-time formulation with matched parameters
(tau derived from the leak rate, refractory from refractory_ms), not a
1:1 mechanical translation (the two runtimes' time semantics differ, so
"equivalent" means "same qualitative LIF behavior with translated
constants", stated honestly rather than claimed exact).

    python pyspike_brian2_export.py    # self-test: generates code for
                                         # agent_brain.spk's actual topology,
                                         # verifies it's syntactically valid
"""
import ast as pyast
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pyspike import Net   # noqa: E402


def export_to_brian2(net: Net, model_name: str = "exported_network") -> str:
    """Generate a standalone Brian2 script string from a pyspike Net's AST.
    Only LIF-type neurons are exported (Resonators use fundamentally
    different, continuously-driven dynamics with no direct Brian2
    NeuronGroup equivalent attempted here -- flagged in the output as a
    comment, not silently dropped)."""
    lif_neurons = [n for n in net.ast.neurons if n.neuron_type != "Resonator"]
    skipped_resonators = [n for n in net.ast.neurons if n.neuron_type == "Resonator"]
    names = [n.name for n in lif_neurons]
    name_index = {n: i for i, n in enumerate(names)}

    lines = [
        "# Auto-generated by pyspike_brian2_export.py -- DO NOT EDIT BY HAND.",
        "# Structurally translated from a pyspike/Spikeling network. See this",
        "# file's module docstring for what has and has NOT been verified.",
        "from brian2 import *",
        "",
        "start_scope()",
        "",
        "# Discrete-tick leak -> continuous-time tau: a neuron with leak L per",
        "# tick loses ~L/threshold of its potential per tick; approximated here",
        "# as an exponential decay time constant. Refractory_ms carries over",
        "# directly (both runtimes use it as an absolute lockout window).",
        "eqs = '''",
        "dv/dt = -v/tau : 1 (unless refractory)",
        "tau : second",
        "vth : 1",
        "'''",
        "",
    ]

    if not lif_neurons:
        lines.append("# No LIF-type neurons in this network -- nothing to export.")
        return "\n".join(lines)

    refractory_ms = net.ast.refractory_ms
    lines.append(f"N = {len(lif_neurons)}")
    lines.append(
        f"{model_name} = NeuronGroup(N, eqs, threshold='v>vth', reset='v=0', "
        f"refractory={refractory_ms}*ms, method='exact')"
    )
    for i, n in enumerate(lif_neurons):
        # tau: bigger leak -> faster decay -> smaller tau. Guard leak=0
        # (no decay -- Brian2 needs a finite tau, so treat it as "very slow").
        tau_ms = 1000.0 / max(n.leak, 1e-6) if n.leak > 0 else 1e6
        lines.append(f"{model_name}.tau[{i}] = {tau_ms:.3f}*ms  # {n.name} (leak={n.leak})")
        lines.append(f"{model_name}.vth[{i}] = {n.threshold}  # {n.name} (threshold={n.threshold})")
    lines.append("")

    if net.ast.connections:
        lines.append(f"{model_name}_syn = Synapses({model_name}, {model_name}, "
                     f"'w : 1', on_pre='v_post += w')")
        pairs = []
        weights = []
        for c in net.ast.connections:
            if c.src not in name_index or c.dst not in name_index:
                continue   # e.g. a connection touching a skipped Resonator
            pairs.append((name_index[c.src], name_index[c.dst]))
            weights.append(c.weight)
        src_idx = ", ".join(str(p[0]) for p in pairs)
        dst_idx = ", ".join(str(p[1]) for p in pairs)
        lines.append(f"{model_name}_syn.connect(i=[{src_idx}], j=[{dst_idx}])")
        lines.append(f"{model_name}_syn.w = {weights!r}")
        lines.append("")

    if skipped_resonators:
        names_skipped = ", ".join(r.name for r in skipped_resonators)
        lines.append(f"# NOT exported (Resonator-type, no direct Brian2 NeuronGroup "
                     f"equivalent attempted): {names_skipped}")
        lines.append("")

    lines.append(f"# run(100*ms)  # uncomment to actually simulate")
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
def _selftest_syntax_valid_on_real_topology() -> None:
    """Export agent_brain.spk's actual topology (built via _build_brain()'s
    own logic, replicated here minimally) and confirm the generated Brian2
    script is syntactically valid Python -- the honest ceiling of what can
    be verified without brian2 installed."""
    net = Net(refractory_ms=40)
    S_Work = net.neuron("S_Work", threshold=50, leak=1)
    S_Ambiguous = net.neuron("S_Ambiguous", threshold=50, leak=1)
    Implementer = net.neuron("Implementer", threshold=50, leak=2)
    Reviewer = net.neuron("Reviewer", threshold=50, leak=2)
    S_Work.to(Implementer, weight=1.2)
    S_Ambiguous.inhibits(Implementer, weight=-2.0)
    Implementer.to(Reviewer, weight=1.2)

    code = export_to_brian2(net, model_name="agent_brain")
    try:
        pyast.parse(code)
        syntax_ok = True
        err = None
    except SyntaxError as e:
        syntax_ok = False
        err = str(e)

    print(f"  [{'PASS' if syntax_ok else 'FAIL'}] generated Brian2 script is syntactically "
          f"valid Python{'' if syntax_ok else f' (error: {err})'}")
    if syntax_ok:
        n_lines = len(code.splitlines())
        print(f"    ({n_lines} lines generated for a 4-neuron, 3-synapse subset of "
              f"agent_brain.spk's topology)")
    return syntax_ok


def _selftest_resonators_flagged_not_silently_dropped() -> None:
    """A Resonator neuron must appear in the output as an explicit comment
    explaining it wasn't exported -- not silently vanish."""
    net = Net()
    A = net.neuron("A", threshold=50, leak=0)
    R = net.neuron("R", type="Resonator", freq_hz=440.0, damping=0.1)
    code = export_to_brian2(net, model_name="mixed")
    ok = "R" in code and "NOT exported" in code
    print(f"  [{'PASS' if ok else 'FAIL'}] Resonator neuron is explicitly flagged as not "
          f"exported, not silently dropped from the output")
    return ok


if __name__ == "__main__":
    print("=" * 78)
    print("  PYSPIKE BRIAN2 EXPORT -- neuromorphic-simulator interop")
    print("=" * 78)
    print("  HONESTY NOTE: brian2 is not installed in this environment. Verified:")
    print("  syntactically valid Python, structurally matches Brian2's documented API.")
    print("  NOT verified: actual numerical execution inside a real Brian2 install.")
    print()
    ok1 = _selftest_syntax_valid_on_real_topology()
    ok2 = _selftest_resonators_flagged_not_silently_dropped()
    print()
    if ok1 and ok2:
        print("  Both checks pass, within the honest limits stated above.")
    else:
        print("  Something failed -- see above.")
