// Auto-generated by spikeling_resonator_verilog.py -- DO NOT EDIT
// Synthesizable fixed-point Resonator bank. See module docstring in
// spikeling_resonator_verilog.py for the fixed-point format notes.

module spikeling_resonators #(
    parameter WIDTH = 32,
    parameter FRAC_BITS = 18,
    parameter ENERGY_WIDTH = 64
) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire signed [WIDTH-1:0] drive,   // one shared sample feeds the whole bank
    output reg  [4:0]         detected
);

    localparam integer N = 5;
    localparam integer DT_SHIFT = 15;
    localparam integer ALPHA_SHIFT = 6;  // derived: dt=2^-15, time_constant=2.50ms -> alpha~=1/64
    localparam signed [WIDTH-1:0] GATE_THRESH = 32'sh0000003f;

    // per-resonator constants, pre-scaled by dt at compile time in Python
    // (see module docstring for why -- omega^2 alone doesn't fit)
    localparam signed [WIDTH-1:0] K1_0 = 32'sh003a4fc7; // Target110 omega^2*dt
    localparam signed [WIDTH-1:0] K2_0 = 32'sh000000dd; // Target110 2*damping*omega*dt
    localparam signed [WIDTH-1:0] K3_0 = 32'sh000005f9; // Target110 coupling*dt
    localparam signed [ENERGY_WIDTH-1:0] THRESH2_0 = 64'sh000000000000abcc; // Target110 threshold^2
    localparam signed [WIDTH-1:0] K1_1 = 32'sh00e93f1b; // Target220 omega^2*dt
    localparam signed [WIDTH-1:0] K2_1 = 32'sh000001ba; // Target220 2*damping*omega*dt
    localparam signed [WIDTH-1:0] K3_1 = 32'sh000017e2; // Target220 coupling*dt
    localparam signed [ENERGY_WIDTH-1:0] THRESH2_1 = 64'sh000000000000abcc; // Target220 threshold^2
    localparam signed [WIDTH-1:0] K1_2 = 32'sh03a4fc6d; // Target440 omega^2*dt
    localparam signed [WIDTH-1:0] K2_2 = 32'sh00000375; // Target440 2*damping*omega*dt
    localparam signed [WIDTH-1:0] K3_2 = 32'sh00005f8a; // Target440 coupling*dt
    localparam signed [ENERGY_WIDTH-1:0] THRESH2_2 = 64'sh000000000000abcc; // Target440 threshold^2
    localparam signed [WIDTH-1:0] K1_3 = 32'sh0e93f1b5; // Target880 omega^2*dt
    localparam signed [WIDTH-1:0] K2_3 = 32'sh000006e9; // Target880 2*damping*omega*dt
    localparam signed [WIDTH-1:0] K3_3 = 32'sh00017e27; // Target880 coupling*dt
    localparam signed [ENERGY_WIDTH-1:0] THRESH2_3 = 64'sh000000000000abcc; // Target880 threshold^2
    localparam signed [WIDTH-1:0] K1_4 = 32'sh3a4fc6d3; // Target1760 omega^2*dt
    localparam signed [WIDTH-1:0] K2_4 = 32'sh00000dd3; // Target1760 2*damping*omega*dt
    localparam signed [WIDTH-1:0] K3_4 = 32'sh0005f89b; // Target1760 coupling*dt
    localparam signed [ENERGY_WIDTH-1:0] THRESH2_4 = 64'sh000000000000abcc; // Target1760 threshold^2

    function signed [WIDTH-1:0] k1_of; input integer idx; begin
        case (idx)
            0: k1_of = K1_0;
            1: k1_of = K1_1;
            2: k1_of = K1_2;
            3: k1_of = K1_3;
            4: k1_of = K1_4;
            default: k1_of = 0;
        endcase
    end endfunction

    function signed [WIDTH-1:0] k2_of; input integer idx; begin
        case (idx)
            0: k2_of = K2_0;
            1: k2_of = K2_1;
            2: k2_of = K2_2;
            3: k2_of = K2_3;
            4: k2_of = K2_4;
            default: k2_of = 0;
        endcase
    end endfunction

    function signed [WIDTH-1:0] k3_of; input integer idx; begin
        case (idx)
            0: k3_of = K3_0;
            1: k3_of = K3_1;
            2: k3_of = K3_2;
            3: k3_of = K3_3;
            4: k3_of = K3_4;
            default: k3_of = 0;
        endcase
    end endfunction

    function signed [ENERGY_WIDTH-1:0] thresh2_of; input integer idx; begin
        case (idx)
            0: thresh2_of = THRESH2_0;
            1: thresh2_of = THRESH2_1;
            2: thresh2_of = THRESH2_2;
            3: thresh2_of = THRESH2_3;
            4: thresh2_of = THRESH2_4;
            default: thresh2_of = {ENERGY_WIDTH{1'b1}};
        endcase
    end endfunction

    // -- state registers: THESE ARE THE RESONATORS --
    reg signed [WIDTH-1:0]        x          [0:N-1];
    reg signed [WIDTH-1:0]        v          [0:N-1];
    reg signed [ENERGY_WIDTH-1:0] energy_ema [0:N-1];

    integer i;

    always @(posedge clk) begin
        if (rst) begin
            for (i = 0; i < N; i = i + 1) begin
                x[i]          <= 0;
                v[i]          <= 0;
                energy_ema[i] <= 0;
                detected[i]   <= 1'b0;
            end
        end else begin
            for (i = 0; i < N; i = i + 1) begin: step
                reg signed [2*WIDTH-1:0] k1x_full, k2v_full, k3drive_full;
                reg signed [WIDTH-1:0]   k1x, k2v, k3drive, v_new, x_new, gated_x;
                reg signed [ENERGY_WIDTH-1:0] x2_full, energy_new;
                reg gate_active, was_above, now_above;

                // accel*dt = -K1*x - K2*v + K3*drive  (each term: Q14.18 * Q14.18 >>> FRAC_BITS)
                k1x_full = $signed(k1_of(i)) * $signed(x[i]);
                k2v_full = $signed(k2_of(i)) * $signed(v[i]);
                k3drive_full = $signed(k3_of(i)) * $signed(drive);
                k1x     = k1x_full     >>> FRAC_BITS;
                k2v     = k2v_full     >>> FRAC_BITS;
                k3drive = k3drive_full >>> FRAC_BITS;

                v_new = v[i] - k1x - k2v + k3drive;
                x_new = x[i] + (v_new >>> DT_SHIFT);   // exact: dt = 2^-DT_SHIFT

                // AMPLITUDE GATING (operand isolation): the mechanical
                // state (x, v) always has to integrate -- a real signal
                // could arrive on any cycle. But when |x_new| is below the
                // noise floor, force the energy multiplier's OPERANDS to
                // zero (gated_x) instead of just ignoring its result --
                // this is the part that actually matters in real silicon:
                // a multiplier fed unchanging zero inputs has near-zero
                // internal switching activity, which is where dynamic
                // power actually goes (NOT instruction/cycle count -- this
                // measured as a WASH in the Python/C benchmarks, see
                // benchmarks/BENCHMARKS.md entry #6; the payoff here is
                // power, a property simulation timing doesn't capture).
                gate_active = (x_new >= GATE_THRESH) || (x_new <= -GATE_THRESH);
                gated_x = gate_active ? x_new : {WIDTH{1'b0}};

                // energy: leaky average of x^2, kept at full Q28.36 width --
                // see module docstring for why this can't be rescaled to Q14.18
                x2_full = $signed(gated_x) * $signed(gated_x);
                was_above = energy_ema[i] >= thresh2_of(i);
                if (gate_active)
                    energy_new = energy_ema[i] + ((x2_full - energy_ema[i]) >>> ALPHA_SHIFT);
                else
                    energy_new = energy_ema[i] - (energy_ema[i] >>> ALPHA_SHIFT);  // decay only, multiplier output unused
                now_above = energy_new >= thresh2_of(i);

                x[i]          <= x_new;
                v[i]          <= v_new;
                energy_ema[i] <= energy_new;
                detected[i]   <= now_above && !was_above;
            end
        end
    end

endmodule
