// Auto-generated by spikeling_resonator_verilog.py -- DO NOT EDIT
// Synthesizable fixed-point Resonator CHAIN with SSH-dimerized nearest-
// neighbor coupling. See generate_coupled_module()'s docstring in
// spikeling_resonator_verilog.py for why this is 2 shared constants
// instead of a stored per-bond weight array.

module spikeling_resonators #(
    parameter WIDTH = 32,
    parameter FRAC_BITS = 18,
    parameter ENERGY_WIDTH = 64
) (
    input  wire                   clk,
    input  wire                   rst,
    input  wire signed [WIDTH-1:0] drive,   // one shared sample feeds the whole bank
    output reg  [7:0]         detected
);

    localparam integer N = 8;
    localparam integer DT_SHIFT = 15;
    localparam integer ALPHA_SHIFT = 6;  // derived: dt=2^-15, time_constant=2.50ms -> alpha~=1/64
    localparam signed [WIDTH-1:0] GATE_THRESH = 32'sh0000003f;

    // CHAIN COUPLING -- 7 bonds specified by exactly 2 constants, not 7.
    // If this were stored per-bond the way K1/K2/K3 are stored per-neuron below, it
    // would need 7 localparams + an O(N) case-statement LUT (see k1_of for what
    // that pattern looks like). SSH dimerization needs only these two, always, at any N.
    localparam signed [WIDTH-1:0] COUPLE_V = 32'sh00002580; // even bonds
    localparam signed [WIDTH-1:0] COUPLE_W = 32'sh00005dc0; // odd bonds

    // per-resonator constants, pre-scaled by dt at compile time in Python
    // (see module docstring for why -- omega^2 alone doesn't fit)
    localparam signed [WIDTH-1:0] K1_0 = 32'sh00e93f1b; // R0 omega^2*dt
    localparam signed [WIDTH-1:0] K2_0 = 32'sh00000452; // R0 2*damping*omega*dt
    localparam signed [WIDTH-1:0] K3_0 = 32'sh000017e2; // R0 coupling*dt
    localparam signed [ENERGY_WIDTH-1:0] THRESH2_0 = 64'sh000000000000abcc; // R0 threshold^2
    localparam signed [WIDTH-1:0] K1_1 = 32'sh00e93f1b; // R1 omega^2*dt
    localparam signed [WIDTH-1:0] K2_1 = 32'sh00000452; // R1 2*damping*omega*dt
    localparam signed [WIDTH-1:0] K3_1 = 32'sh000017e2; // R1 coupling*dt
    localparam signed [ENERGY_WIDTH-1:0] THRESH2_1 = 64'sh000000000000abcc; // R1 threshold^2
    localparam signed [WIDTH-1:0] K1_2 = 32'sh00e93f1b; // R2 omega^2*dt
    localparam signed [WIDTH-1:0] K2_2 = 32'sh00000452; // R2 2*damping*omega*dt
    localparam signed [WIDTH-1:0] K3_2 = 32'sh000017e2; // R2 coupling*dt
    localparam signed [ENERGY_WIDTH-1:0] THRESH2_2 = 64'sh000000000000abcc; // R2 threshold^2
    localparam signed [WIDTH-1:0] K1_3 = 32'sh00e93f1b; // R3 omega^2*dt
    localparam signed [WIDTH-1:0] K2_3 = 32'sh00000452; // R3 2*damping*omega*dt
    localparam signed [WIDTH-1:0] K3_3 = 32'sh000017e2; // R3 coupling*dt
    localparam signed [ENERGY_WIDTH-1:0] THRESH2_3 = 64'sh000000000000abcc; // R3 threshold^2
    localparam signed [WIDTH-1:0] K1_4 = 32'sh00e93f1b; // R4 omega^2*dt
    localparam signed [WIDTH-1:0] K2_4 = 32'sh00000452; // R4 2*damping*omega*dt
    localparam signed [WIDTH-1:0] K3_4 = 32'sh000017e2; // R4 coupling*dt
    localparam signed [ENERGY_WIDTH-1:0] THRESH2_4 = 64'sh000000000000abcc; // R4 threshold^2
    localparam signed [WIDTH-1:0] K1_5 = 32'sh00e93f1b; // R5 omega^2*dt
    localparam signed [WIDTH-1:0] K2_5 = 32'sh00000452; // R5 2*damping*omega*dt
    localparam signed [WIDTH-1:0] K3_5 = 32'sh000017e2; // R5 coupling*dt
    localparam signed [ENERGY_WIDTH-1:0] THRESH2_5 = 64'sh000000000000abcc; // R5 threshold^2
    localparam signed [WIDTH-1:0] K1_6 = 32'sh00e93f1b; // R6 omega^2*dt
    localparam signed [WIDTH-1:0] K2_6 = 32'sh00000452; // R6 2*damping*omega*dt
    localparam signed [WIDTH-1:0] K3_6 = 32'sh000017e2; // R6 coupling*dt
    localparam signed [ENERGY_WIDTH-1:0] THRESH2_6 = 64'sh000000000000abcc; // R6 threshold^2
    localparam signed [WIDTH-1:0] K1_7 = 32'sh00e93f1b; // R7 omega^2*dt
    localparam signed [WIDTH-1:0] K2_7 = 32'sh00000452; // R7 2*damping*omega*dt
    localparam signed [WIDTH-1:0] K3_7 = 32'sh000017e2; // R7 coupling*dt
    localparam signed [ENERGY_WIDTH-1:0] THRESH2_7 = 64'sh000000000000abcc; // R7 threshold^2

    function signed [WIDTH-1:0] k1_of; input integer idx; begin
        case (idx)
            0: k1_of = K1_0;
            1: k1_of = K1_1;
            2: k1_of = K1_2;
            3: k1_of = K1_3;
            4: k1_of = K1_4;
            5: k1_of = K1_5;
            6: k1_of = K1_6;
            7: k1_of = K1_7;
            default: k1_of = 0;
        endcase
    end endfunction

    function signed [WIDTH-1:0] k2_of; input integer idx; begin
        case (idx)
            0: k2_of = K2_0;
            1: k2_of = K2_1;
            2: k2_of = K2_2;
            3: k2_of = K2_3;
            4: k2_of = K2_4;
            5: k2_of = K2_5;
            6: k2_of = K2_6;
            7: k2_of = K2_7;
            default: k2_of = 0;
        endcase
    end endfunction

    function signed [WIDTH-1:0] k3_of; input integer idx; begin
        case (idx)
            0: k3_of = K3_0;
            1: k3_of = K3_1;
            2: k3_of = K3_2;
            3: k3_of = K3_3;
            4: k3_of = K3_4;
            5: k3_of = K3_5;
            6: k3_of = K3_6;
            7: k3_of = K3_7;
            default: k3_of = 0;
        endcase
    end endfunction

    function signed [ENERGY_WIDTH-1:0] thresh2_of; input integer idx; begin
        case (idx)
            0: thresh2_of = THRESH2_0;
            1: thresh2_of = THRESH2_1;
            2: thresh2_of = THRESH2_2;
            3: thresh2_of = THRESH2_3;
            4: thresh2_of = THRESH2_4;
            5: thresh2_of = THRESH2_5;
            6: thresh2_of = THRESH2_6;
            7: thresh2_of = THRESH2_7;
            default: thresh2_of = {ENERGY_WIDTH{1'b1}};
        endcase
    end endfunction

    // bond parity select -- 1-bit, NOT a case-statement LUT: bond j (between
    // resonator j and j+1) uses COUPLE_V if j is even, COUPLE_W if j is odd.
    function signed [WIDTH-1:0] bond_of; input integer j; begin
        bond_of = (j[0] == 1'b0) ? COUPLE_V : COUPLE_W;
    end endfunction

    // -- state registers: THESE ARE THE RESONATORS --
    reg signed [WIDTH-1:0]        x          [0:N-1];
    reg signed [WIDTH-1:0]        v          [0:N-1];
    reg signed [ENERGY_WIDTH-1:0] energy_ema [0:N-1];

    integer i;

    always @(posedge clk) begin
        if (rst) begin
            for (i = 0; i < N; i = i + 1) begin
                x[i]          <= 0;
                v[i]          <= 0;
                energy_ema[i] <= 0;
                detected[i]   <= 1'b0;
            end
        end else begin
            for (i = 0; i < N; i = i + 1) begin: step
                reg signed [2*WIDTH-1:0] k1x_full, k2v_full, k3drive_full;
                reg signed [2*WIDTH-1:0] cleft_full, cright_full;
                reg signed [WIDTH-1:0]   k1x, k2v, k3drive, cleft, cright, v_new, x_new, gated_x;
                reg signed [ENERGY_WIDTH-1:0] x2_full, energy_new;
                reg gate_active, was_above, now_above;

                k1x_full = $signed(k1_of(i)) * $signed(x[i]);
                k2v_full = $signed(k2_of(i)) * $signed(v[i]);
                k3drive_full = $signed(k3_of(i)) * $signed(drive);
                k1x     = k1x_full     >>> FRAC_BITS;
                k2v     = k2v_full     >>> FRAC_BITS;
                k3drive = k3drive_full >>> FRAC_BITS;

                // nearest-neighbor coupling: bond (i-1) to the left, bond i to the right
                cleft_full  = (i > 0)     ? ($signed(bond_of(i-1)) * $signed(x[i-1])) : 0;
                cright_full = (i < N - 1) ? ($signed(bond_of(i))   * $signed(x[i+1])) : 0;
                cleft  = cleft_full  >>> FRAC_BITS;
                cright = cright_full >>> FRAC_BITS;

                v_new = v[i] - k1x - k2v + k3drive + cleft + cright;
                x_new = x[i] + (v_new >>> DT_SHIFT);

                gate_active = (x_new >= GATE_THRESH) || (x_new <= -GATE_THRESH);
                gated_x = gate_active ? x_new : {WIDTH{1'b0}};

                x2_full = $signed(gated_x) * $signed(gated_x);
                was_above = energy_ema[i] >= thresh2_of(i);
                if (gate_active)
                    energy_new = energy_ema[i] + ((x2_full - energy_ema[i]) >>> ALPHA_SHIFT);
                else
                    energy_new = energy_ema[i] - (energy_ema[i] >>> ALPHA_SHIFT);
                now_above = energy_new >= thresh2_of(i);

                x[i]          <= x_new;
                v[i]          <= v_new;
                energy_ema[i] <= energy_new;
                detected[i]   <= now_above && !was_above;
            end
        end
    end

endmodule
