// Auto-generated by spikeling_resonator_verilog.py -- DO NOT EDIT
// Self-checking testbench: replays a precomputed mixed signal through
// the Resonator bank and verifies detections match expectations --
// same scenario as core/examples/test_tone_detector.py and .c.
`timescale 1ns/1ps

module tb;
    localparam N = 8;
    localparam STEPS = 4000;
    localparam WIDTH = 32;

    reg clk = 0;
    reg rst = 1;
    reg signed [WIDTH-1:0] drive_mem [0:STEPS-1];
    reg signed [WIDTH-1:0] drive;
    wire [N-1:0] detected;

    spikeling_resonators dut (.clk(clk), .rst(rst), .drive(drive), .detected(detected));

    always #5 clk = ~clk;  // 100 MHz

    reg [127:0] names [0:N-1];
    initial names[0] = "R0";
    initial names[1] = "R1";
    initial names[2] = "R2";
    initial names[3] = "R3";
    initial names[4] = "R4";
    initial names[5] = "R5";
    initial names[6] = "R6";
    initial names[7] = "R7";

    integer fired [0:N-1];
    integer i, t;

    initial begin
        $readmemh("chain_drive.hex", drive_mem);
        for (i = 0; i < N; i = i + 1) fired[i] = 0;
        @(negedge clk); rst = 0;
        for (t = 0; t < STEPS; t = t + 1) begin
            drive = drive_mem[t];
            @(negedge clk);
            for (i = 0; i < N; i = i + 1) begin
                if (detected[i]) begin
                    $display("[SPIKE] %0s fired at step %0d", names[i], t);
                    fired[i] = 1;
                end
            end
        end

        $display("");
        $display("[test] final fired state:");
        for (i = 0; i < N; i = i + 1) begin
            $display("  %0s  fired=%0d", names[i], fired[i]);
        end

        // pass/fail check baked in at generation time from expected_actions
        begin : check_block
            integer ok;
            ok = 1;
            if (!fired[0]) begin $display("[test] FAIL -- missing expected detection: %0s", names[0]); ok = 0; end
            if (!fired[7]) begin $display("[test] FAIL -- missing expected detection: %0s", names[7]); ok = 0; end
            if (ok) $display("\n[test] PASS -- Resonator Verilog hardware module correctly detected the expected tones with no false positives.");
        end
        $finish;
    end
endmodule
