/* Auto-generated by Spikeling Compiler — DO NOT EDIT */
#ifndef SPIKELING_HW_H
#define SPIKELING_HW_H

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <math.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ── Neuron ── */
typedef struct {
    const char* name;
    uint32_t    threshold;
    uint32_t    leak;
    float       membrane_potential;
    float       last_spike_time;
    uint32_t    fire_count;
} Neuron;

/* ── Synapse ── */
typedef struct {
    uint32_t src_idx;
    uint32_t dst_idx;
    float    weight;
} Synapse;

/* ── Resonator ──
 * A damped harmonic oscillator tuned to freq_hz, for frequency-selective
 * detection (e.g. telling a specific tone/signature apart from other
 * tones + noise) -- not pulsed like Neuron, continuously driven via
 * spikeling_resonator_step(). See runtime/runtime.py's ResonatorState
 * for the Python reference implementation this mirrors; gain is
 * normalized by coupling ~ omega^2 so higher-frequency channels in the
 * same bank don't respond weaker than low-frequency ones (measured in
 * resonator-prototype/resonator_bank.py). */
typedef struct {
    const char* name;
    float       freq_hz;
    float       damping;
    float       coupling;
    float       threshold;   /* RMS-amplitude level that counts as "detected" */
    float       gate_threshold; /* |x| below this: skip the x*x energy multiply */
    float       energy_time_constant; /* seconds -- see spikeling_resonator_step()'s
                                          comment for why this must scale with dt,
                                          not be a fixed per-step decay constant */
    float       x;
    float       v;
    float       energy_ema;  /* mean-square amplitude, exponential moving average */
} Resonator;

/* ── Network dimensions ── */
#define NEURON_COUNT     0
#define SYNAPSE_COUNT    0
#define RESONATOR_COUNT  5
#define REFRACTORY_MS    0
#define LEARN_RATE       0.01f

/* ── Neuron table ── */
extern Neuron     neurons[NEURON_COUNT];
extern Synapse    synapses[SYNAPSE_COUNT];
extern Resonator  resonators[RESONATOR_COUNT];

/* ── Spike dispatch ── */
void spikeling_tick(uint32_t neuron_idx, float current_time_ms);
void spikeling_stdp_update(uint32_t pre_idx, uint32_t post_idx, float dt);

/* Advance one Resonator by one timestep with a shared drive signal
 * (e.g. an audio sample). Returns 1 the instant it crosses its
 * detection threshold (edge-triggered, like a neuron firing), else 0. */
int spikeling_resonator_step(uint32_t resonator_idx, float drive, float dt, float current_time_ms);

#endif /* SPIKELING_HW_H */
