/* Auto-generated by Spikeling Compiler — DO NOT EDIT */
#include "spikeling_hw.h"
#include <math.h>

/* ── Neuron definitions ── */
Neuron neurons[NEURON_COUNT] = {
    /* none */
};

/* ── Synapse definitions ── */
Synapse synapses[SYNAPSE_COUNT] = {
    /* none */
};

/* ── Action dispatch table ── */
static const char* action_table[NEURON_COUNT] = {
    /* none */
};

/* ── Resonator definitions ── */
Resonator resonators[RESONATOR_COUNT] = {
    {"Target110", 110.0f, 0.02f, 191.07554120509f, 0.0008f, 0.00024f, 0.0025f, 0.0f, 0.0f, 0.0f},
    {"Target220", 220.0f, 0.02f, 764.30216482036f, 0.0008f, 0.00024f, 0.0025f, 0.0f, 0.0f, 0.0f},
    {"Target440", 440.0f, 0.02f, 3057.20865928144f, 0.0008f, 0.00024f, 0.0025f, 0.0f, 0.0f, 0.0f},
    {"Target880", 880.0f, 0.02f, 12228.83463712576f, 0.0008f, 0.00024f, 0.0025f, 0.0f, 0.0f, 0.0f},
    {"Target1760", 1760.0f, 0.02f, 48915.33854850304f, 0.0008f, 0.00024f, 0.0025f, 0.0f, 0.0f, 0.0f}
};

/* ── Resonator action dispatch table ── */
static const char* resonator_action_table[RESONATOR_COUNT] = {
    "TONE_110HZ",
    "TONE_220HZ",
    "TONE_440HZ",
    "TONE_880HZ",
    "TONE_1760HZ"
};

/* ── Spike tick ── */
void spikeling_tick(uint32_t idx, float current_time_ms) {
    Neuron* n = &neurons[idx];
    float elapsed = current_time_ms - n->last_spike_time;

    if (elapsed < REFRACTORY_MS) {
        return;  /* Refractory lockout */
    }

    /* Leak */
    n->membrane_potential -= n->leak;
    if (n->membrane_potential < 0) n->membrane_potential = 0;

    /* Threshold check */
    n->membrane_potential += n->threshold + 1;  /* simulated input drive */
    if (n->membrane_potential >= n->threshold) {
        n->membrane_potential = 0;
        n->last_spike_time    = current_time_ms;
        n->fire_count++;

        /* Emit action */
        if (action_table[idx]) {
            printf("[SPIKE] %s -> %s\n", n->name, action_table[idx]);
        }

        /* Propagate to downstream synapses */
        for (int s = 0; s < SYNAPSE_COUNT; s++) {
            if (synapses[s].src_idx == idx) {
                neurons[synapses[s].dst_idx].membrane_potential +=
                    synapses[s].weight * 50.0f;
            }
        }
    }
}

/* ── Resonator step ──
 * SAMPLE-RATE BUG, FOUND AND FIXED: the energy EMA's decay rate must be
 * derived from dt and energy_time_constant, not a fixed per-step
 * constant -- a fixed 0.01f implicitly assumes whatever dt it was tuned
 * at (here, 2.5e-5s / 40kHz). Run this at a different sample rate (e.g.
 * 1MHz, needed to accurately resolve a 40kHz signal -- see
 * a separate 40kHz resonator sample-rate test) without rescaling,
 * and the averaging window silently shrinks far below this resonator's
 * own settling time, which collapsed Python-side detection accuracy
 * from ~99% to ~45%/0%-recall before this was caught and fixed there
 * first (see runtime.ResonatorState.step's docstring for the full
 * story). Mirrored here for parity. */
int spikeling_resonator_step(uint32_t idx, float drive, float dt, float current_time_ms) {
    Resonator* r = &resonators[idx];
    float omega = 2.0f * (float)M_PI * r->freq_hz;
    float accel = -(omega * omega) * r->x - 2.0f * r->damping * omega * r->v;
    accel += r->coupling * drive;
    r->v += accel * dt;
    r->x += r->v * dt;

    float alpha = dt / r->energy_time_constant;
    if (alpha > 1.0f) alpha = 1.0f;

    float was_above = sqrtf(r->energy_ema) >= r->threshold;
    /* Amplitude gating: skip the x*x multiply when |x| is below the
     * noise floor (see runtime.ResonatorState.step's docstring for the
     * full rationale + benchmarks/BENCHMARKS.md entry #6). Measured to
     * be a wash on a CPU (~1.0x, modern multiply units are already
     * pipelined/cheap) -- kept here only for behavioral parity with the
     * Python runtime, not as a performance claim for this backend. */
    if (fabsf(r->x) >= r->gate_threshold) {
        r->energy_ema += alpha * (r->x * r->x - r->energy_ema);
    } else {
        r->energy_ema -= alpha * r->energy_ema;
    }
    float now_above = sqrtf(r->energy_ema) >= r->threshold;

    if (now_above && !was_above) {
        if (resonator_action_table[idx]) {
            printf("[SPIKE] %s -> %s  (t=%.2fms)\n", r->name, resonator_action_table[idx], current_time_ms);
        }
        return 1;
    }
    return 0;
}

/* ── STDP weight update ── */
void spikeling_stdp_update(uint32_t pre_idx, uint32_t post_idx, float dt) {
    float delta = LEARN_RATE * expf(-fabsf(dt) / 20.0f);
    for (int s = 0; s < SYNAPSE_COUNT; s++) {
        if (synapses[s].src_idx == pre_idx && synapses[s].dst_idx == post_idx) {
            synapses[s].weight += (dt > 0) ? delta : -delta * 0.5f;
            if (synapses[s].weight > 1.0f) synapses[s].weight = 1.0f;
            if (synapses[s].weight < 0.0f) synapses[s].weight = 0.0f;
        }
    }
}
